# Aquí comienza el Sync Hook (PreSync) que se ejecutará antes del despliegue
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-apache-job
  annotations:
    argocd.argoproj.io/hook: PreSync  # La anotación argocd.argoproj.io/hook: PreSync le dice a ArgoCD que este Job debe ejecutarse antes de que se despliegue la aplicación (en este caso, antes de que Apache se inicie).
spec:
  template:
    spec:
      containers:
      - name: pre-sync-job
        image: busybox  #Usa la imagen BusyBox, que es una imagen minimalista de Linux, ideal para ejecutar comandos simples.
        command: ['sh', '-c', 'echo PreSync Job running before Apache deployment']
      restartPolicy: Never
